name: Build and publish STABLE docker contaier

on:
  push:
    tags:
      - "v*.*.*"
    paths-ignore:
      - README.md
      - .gitignore
      - .github/workflows/**

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_DOCKER_BUILD_TOKEN }}

      - name: Get tag name
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.get_tag.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest
