name: Build and publish UNSTABLE docker contaier

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore
      - .github/workflows/**
  workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_DOCKER_BUILD_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/vargylet/kaellare-dev:latest
