name: HTML Linting

on:
  push:
  workflow_dispatch:

jobs:
  html-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install HTML Linting Tool
        run: npm install htmlhint

      - name: Run HTML linting
        run: npx htmlhint "**/*.html"
