name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: stable

    - name: Login to GitHub Packages
      run: echo ${{ secrets.GH_DOCKER_BUILD_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t docker.pkg.github.com/${{ github.repository }}/min-container:latest .
        docker push docker.pkg.github.com/${{ github.repository }}/min-container:latest
